### PR TITLE
Bugfix: empty 2nd line detection

### PR DESCRIPTION
**Pull request by asfaltboy**
This PR depends on #7 since I was doing these incrementally, and before that PR there are no tests.

### CODE REVIEW

**Comment by divmain** [comment]
@asfaltboy, could you rebase on top of master and force push?  I can't tell what's being changed here.  Alternately, are there particular commits I could cherry-pick?

**Comment by asfaltboy** [comment]
There we go, only 1 commit to review now :)

**Comment by divmain** [comment]
Yikes. No wonder you wanted to add tests. This is great, thanks again!

**Comment by asfaltboy** [comment]
Typos are a natural behaviour of code 😄 , though honestly I just wanted to try it out since it's been a while since I touched JS

**Pull request merged**
